name: Continuous Integration
on:
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: michaelw90/PHP-Lint@master

  discord:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Discord notification
        uses: sarisia/actions-status-discord@v1
        if: always()
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          status: ${{ job.status }}
          title: "CI - Pull Request"
          description: "Build finalizado para PR na branch main"
          color: ${{ job.status == 'success' && '0x00ff00' || '0xff0000' }}
