name: Continuous Integration
on:
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: michaelw90/PHP-Lint@master

  discord:
    runs-on: ubuntu-latest
    steps:
      - uses: Sniddl/discord-commits@v1.8
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          template: "avatar-with-link"
          include-extras: true
